#!/usr/bin/python3
from pyppeteer import launch
from gherkin_parser.parser import parse_from_filename, parse_file, parse_lines
import asyncio, coloredlogs, imp, logging, os, sys, yaml
from pyppetheater import run_test

run_test(sys.argv[1])
